### ISSUE TITLE
Tracker::update() always returns true

### ISSUE THREAD

**Issue by berak** [opencv/opencv_contrib#1121]
##### System information (version)
- OpenCV => 3.2 (latest master)
- Operating System / Platform => any
- Compiler => any

[Tracker::update](http://docs.opencv.org/master/d0/d0a/classcv_1_1Tracker.html#a6b2bc1d8bf400424a883367edc94dbcf) should return false, if it lost the object, but both the KCF and the GOTURN implementation always return true, so we can never find out, if it's nessecary to re-initialize it.

**Comment by sovrasov** [comment]
For KCF this feature can be done using confidence thresholding. Take a look at #1123.

**Comment by sovrasov** [comment]
I think GOTURN net can't give us a confidence of detection. @Auron-X am I right?

**Comment by Auron-X** [comment]
@sovrasov GOTURN was designed for tracking purposes and does not support detection. Although it can be trained in the same manner for detection task on object detection dataset, but in this case it will be closer to R-CNN net from which I believe GOTURN took inspiration

**Comment by Auron-X** [comment]
If you are asking about the confidence of tracking, then yes GOTURN and KCF algorithms has no mechanism to detect when tracker fails, because tracker needs some analog of Ground Truth - it can be target model, or detector that runs in parallel. For ex. TLD tracker includes all 3: Tracking, Learning (Model), Detection so it can 'correct' tracker errors in some way
