### ISSUE TITLE
(dnn/tensorflow) Unknown layer type Shape in op Flatten/Shape

### ISSUE THREAD

**Issue by wilcoschoneveld** [opencv/opencv_contrib#1241]
I'm trying to run a CNN via opencv with the dnn module. However, I'm getting an error when attempting to import the frozen model with the TensorflowImporter. I tested on tag 3.2.0 and master.

OpenCV Error: Unspecified error (Unknown layer type Shape in op Flatten/Shape)

I created and trained the model using Tensorflow (1.2.0rc0) and the Keras API (bundled as tensorflow.contrib.keras). I saved the graph and checkpoints and froze the model with freeze_graph.

I do see a 'Reshape' op specified in the tf_importer.cpp, could it be that this has been renamed to 'Shape' which is not supported by the importer yet?

@arrybn 

Thanks!

**Comment by alalek** [comment]
> OpenCV tag 3.2.0

Perhaps you should try the latest master at first (update both opencv/opencv_contrib repositories). DNN module has been actively updated since 3.2.

**Comment by wilcoschoneveld** [comment]
Thanks for the tip. Just tested it but same error

**Comment by arrybn** [comment]
@wilcoschoneveld could you share your model or some simplified version of it which reproduces the issue?

**Comment by wilcoschoneveld** [comment]
This is what I used to generate the model:
```python
model = keras.models.Sequential(name='Opticflow')

model.add(Conv2D(
    name='Conv1',
    filters=32,
    kernel_size=(5, 5),
    strides=2,
    activation='relu',
    input_shape=(64, 64, 2)))

model.add(Conv2D(
    name='Conv2',
    filters=32,
    kernel_size=(3, 3),
    strides=2,
    activation='relu'))

model.add(Conv2D(
    name='Conv3',
    filters=32,
    kernel_size=(3, 3),
    strides=2,
    activation='relu'))

model.add(Flatten(name='Flatten'))

model.add(Dense(10, name='Hidden'))

model.add(Dense(2, name='Output'))

model.summary()

model.compile(loss=keras.losses.mean_squared_error,
              optimizer=keras.optimizers.Adam(lr=1e-4))

```

and here are the files:
[freeze.zip](https://github.com/opencv/opencv_contrib/files/1091200/freeze.zip)

Thanks!

**Comment by arrybn** [comment]
I will take a look soon

**Comment by wilcoschoneveld** [comment]
@arrybn any updates? :)

**Comment by arrybn** [comment]
@wilcoschoneveld, I found out what are origins of the issue. You used
`model.add(Flatten(name='Flatten'))`
line in your script for turning tensor into vector. 
Keras transformed your code into 5 operations:
```
shape()
strided_slice()
prod()
pack()
reshape()
```
First 4 ops are needed for computing length of the resulting vector. Shape of tensor is taken, [H,W,C] vector with dimensions is cut from [N, H, W, C] shape() resulting vector, then H*W*C multiplication is computed and passed as a parameter for reshape() op.
For now the dnn doesn't support  these first 4 ops. And actually it's not a big deal to add the missed layer. The issue is we have to redesign the dnn to add pre-inference computing of "constant" layers. Indeed, outputs of these 5 layers can be computed if we know input shape for our model.
Current implementation doesn't allow to inference a model with such structure of layers inside because we need to know all shapes of all layers before making a forward pass.
For now it takes a lot of work to incorporate support of such constructions.
But I think there is a workaround. I think you can replace the line in your script by
`tf.reshape()`
with hard-coded dimensions.
I understand that the result will be uglier and less convenient to support. We are planning to change internal architecture of the module. 
Please let me know if it's possible to use tf.reshape() in your code

**Comment by wilcoschoneveld** [comment]
I understand the complexity of this problem. Thanks for providing a workaround; it is possible to use  `tf.reshape` in my setup. I'm closing this issue for now. Thanks again!
