### ISSUE TITLE
What version of contrib is suitable for OpenCV 3.0.0 alpha

### ISSUE THREAD

**Issue by RichieLee93** [opencv/opencv_contrib#1392]
As the title shows, it makes me confused about which version of contrib should I use since there are two types: 3.0.0 and 3.0.0rc1.
Thank you

**Comment by alalek** [comment]
There is no tags for opencv-contrib for 3.3.0-alpha.
Avoid using of OpenCV 3.0.0 alpha ("beta", "rc" - the same note).
Consider to use 3.0.0 or latest 3.x version (3.3 at this moment) because OpenCV 3.0.0 is too old (3+ years).

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
