### ISSUE TITLE
Cannot Reproduce Results of Feature Matching with FLANN Tutorial

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#1595]
opencv_contrib 3.4.1-dev
VS 2017 win64

Detailed description : see http://answers.opencv.org/question/187947/cannot-reproduce-results-of-feature-matching-with-flann-tutorial/

**Comment by berak** [comment]
i think, we can close this issue, since @catree replaced the inline code in the tutorial with [a sample using proper knn_match()](https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/features2D/feature_flann_matcher/SURF_FLANN_matching_Demo.cpp) . so, same (good!) results for c++, python java.

thanks again for the heroic effort there, @catree !
