### ISSUE TITLE
Kinfu general params constructor (python)

### ISSUE THREAD

**Issue by Brainmuck** [opencv/opencv_contrib#1903]
##### System information (version)

- OpenCV => 4 beta
- Operating System / Platform => ubuntu 16.04
- Compiler => :grey_question:

##### Detailed description

Would it be possible to add a general Params constructor.  I am using a realsense camera in python and can't seem to modify some of the parameters (intrinsics) created by defaultParams() or coarseParams().  

I managed to get the realsense working by modifying defaultParams() function and recompiling but a function that would take input parameters would be useful.   Unless I am missing something and there is an easier way to do it.

**Comment by scimad** [comment]
Same query here. How do we modify the parameters to use Azure-Kinect camera?

**Comment by scimad** [comment]
Apparently, 75bcd397af4d243aa6ddaabe3d935e41fe6c8c04 removes the function setParams() from kinfu. And the commit message says " `KinFu::setParams()` removed since it has no effect anyway". Can you elaborate why this was done? @alalek or @savuor

**Comment by savuor** [comment]
@scimad the method `setParams()` was removed from `KinFu` class because of the reason mentioned in the commit message: it has no effect.
Indeed, aside from thresholds and other coefficients it contains values like frame size, volume size and dimensions. These parameters can't be changed on the fly, the whole pipeline should be reset. This is why the KinFu should be created from a new set of params each time.
Talking of Python constructor for params, this should be done but I do not have enough time for that now. If you know how to change the code to add a constructor, feel free to file a PR.

**Comment by ayushgargdroid** [comment]
I will create a PR for this issue.

**Comment by hwy1992129** [comment]
@ayushgargdroid Hello, are there any examples for Kinfu in the python version?
