### ISSUE TITLE
Scene_reconstruction cannot be compiled 

### ISSUE THREAD

**Issue by eliasarellano** [opencv/opencv_contrib#1924]
@edgarriba @mshabunin @LaurentBerger @GSORF 
Hello everyone.
I'm trying to compile the scene_reconstruction example from the folder modules/sfm/samples , 
I have installed a later opencv version than 3.1, in Ubuntu 16.04 LTS 64bit compiling with g++.
I also installed SFM with the commands explained in the README.md in SFM folder.
My question is How do I have to organize hpp files :
#include <opencv2/sfm.hpp>
#include <opencv2/viz.hpp>
#include <opencv2/calib3d.hpp>
#include <opencv2/core.hpp>
to make that work? or How do I use Cmake in this case?  because always there is a file that is not declared or something missing in include libraries.
Thank you for all your job, I know that in my problem something really simple is missing, thanks.

**Comment by GSORF** [comment]
Hello @eliasarellano,

sorry, I have no idea. I didn't even manage to compile the sfm module yet (I am mainly using Windows at the moment and libMV has crazy dependencies). I did not put much time into that until now, therefore I am not able to help you at this specific moment.

Kind regards,
Adam

**Comment by eliasarellano** [comment]
> Hello @eliasarellano,
> 
> sorry, I have no idea. I didn't even manage to compile the sfm module yet (I am mainly using Windows at the moment and libMV has crazy dependencies). I did not put much time into that until now, therefore I am not able to help you at this specific moment.
> 
> Kind regards,
> Adam

Hello @GSORF 
Thank you for your answer, actually sfm is not for windows, only linux, but thank you I'll keep trying and if I have the solution I will post here the results :).

Kind regards,
Elias

**Comment by liqing1993** [comment]
I also meet this problem, have you solved it?

**Comment by eliasarellano** [comment]
> I also meet this problem, have you solved it?

Yes, finally I resolved that, I come here to make things more clear :) 
First: the user @mshabunin has posted in this problem `https://github.com/opencv/opencv_contrib/issues/779` How to compile and execute Scene_construction.

 You have to follow its instructions here `https://github.com/opencv/opencv_contrib/issues/779#issuecomment-343505336` but pay attention on this:
1) I advice to you to have more than 10 GB FREE in the disk, because would be installing OpenCV and OpenCV_contrib at the same time,  OpenCV contrib is a git repository that contains all kind of code and libraries made by developpers (one of the code is Scene cosntruction)
2) Something that you should also install is the VIZ for linux, for that install VTK, here is the link of instructions `https://www.vtk.org/Wiki/VTK/Building/Linux` (if you don't use QT4 on linux and only use the terminal, just follow the "Configure" and "Build". the VIZ is the tool used by scene_construction to show in a windows the point cloud in a 3D environnement.
3) Install opencv FROM THE GIT REPOSITORY, I advice to you that because I tried doing this installation with an older version of Opencv (that was 3.4.4) downloaded  from the website and it didn't work at the end of the installation, scene_construction wasn't compiled :(. But finally I used the opencv from git and it worked, si follow the step 2 from the instruction "Clone OpenCV sources: git clone https://github.com/opencv/opencv && git clone https://github.com/opencv/opencv_contrib"
4) Try the step 4, but personally I did that `cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -DBUILD_EXAMPLES=ON -D CMAKE_INSTALL_PREFIX=/usr/local ../opencv` because puting /usr/local prefix means that you install libraries in a default folder, I guess that, I'm not sure ajhajhaj. If it doesn't work , just separate "-D" from the next word.
5) If during the building part you have a proble of c++11 missing, go to the cmakefile.txt and add this line `SET(CMAKE_CXX_FLAGS "-std=c++11 -O3")` wherever you want.

I could say that it's ONLY WORKS ON LINUX, one of those libraries only works on linux, I don't remember what library is. SFM scene construction is also posible on windows because there are softwares that works there, but I still don't know how.

Good luck :).

**Comment by liqing1993** [comment]
Thank you very much for your advice! hope it work for me-------- 原始邮件 --------主题：Re: [opencv/opencv_contrib] Scene_reconstruction cannot be compiled  (#1924)发件人：eliasarellano 收件人：opencv/opencv_contrib 抄送：liqing1993 <332591632@qq.com>,Comment 
I also meet this problem, have you solved it?

Yes, finally I resolved that, I come here to make things more clear :)
First: the user @mshabunin has posted in this problem https://github.com/opencv/opencv_contrib/issues/779 How to compile and execute Scene_construction.
You have to follow its instructions here https://github.com/opencv/opencv_contrib/issues/779#issuecomment-343505336 but pay attention on this:

I advice to you to have more than 10 GB FREE in the disk, because would be installing OpenCV and OpenCV_contrib at the same time,  OpenCV contrib is a git repository that contains all kind of code and libraries made by developpers (one of the code is Scene cosntruction)
Something that you should also install is the VIZ for linux, for that install VTK, here is the link of instructions https://www.vtk.org/Wiki/VTK/Building/Linux (if you don't use QT4 on linux and only use the terminal, just follow the "Configure" and "Build". the VIZ is the tool used by scene_construction to show in a windows the point cloud in a 3D environnement.
Install opencv FROM THE GIT REPOSITORY, I advice to you that because I tried doing this installation with an older version of Opencv (that was 3.4.4) downloaded  from the website and it didn't work at the end of the installation, scene_construction wasn't compiled :(. But finally I used the opencv from git and it worked, si follow the step 2 from the instruction "Clone OpenCV sources: git clone https://github.com/opencv/opencv && git clone https://github.com/opencv/opencv_contrib"
Try the step 4, but personally I did that cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -DBUILD_EXAMPLES=ON -D CMAKE_INSTALL_PREFIX=/usr/local ../opencv because puting /usr/local prefix means that you install libraries in a default folder, I guess that, I'm not sure ajhajhaj. If it doesn't work , just separate "-D" from the next word.
If during the building part you have a proble of c++11 missing, go to the cmakefile.txt and add this line SET(CMAKE_CXX_FLAGS "-std=c++11 -O3") wherever you want.

I could say that it's ONLY WORKS ON LINUX, one of those libraries only works on linux, I don't remember what library is. SFM scene construction is also posible on windows because there are softwares that works there, but I still don't know how.
Good luck :).

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opencv/opencv_contrib","title":"opencv/opencv_contrib","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/opencv/opencv_contrib"}},"updates":{"snippets":[{"icon":"PERSON","message":"@eliasarellano in #1924: \u003e I also meet this problem, have you solved it?\r\n\r\nYes, finally I resolved that, I come here to make things more clear :) \r\nFirst: the user @mshabunin has posted in this problem `https://github.com/opencv/opencv_contrib/issues/779` How to compile and execute Scene_construction.\r\n\r\n You have to follow its instructions here `https://github.com/opencv/opencv_contrib/issues/779#issuecomment-343505336` but pay attention on this:\r\n1) I advice to you to have more than 10 GB FREE in the disk, because would be installing OpenCV and OpenCV_contrib at the same time,  OpenCV contrib is a git repository that contains all kind of code and libraries made by developpers (one of the code is Scene cosntruction)\r\n2) Something that you should also install is the VIZ for linux, for that install VTK, here is the link of instructions `https://www.vtk.org/Wiki/VTK/Building/Linux` (if you don't use QT4 on linux and only use the terminal, just follow the \"Configure\" and \"Build\". the VIZ is the tool used by scene_construction to show in a windows the point cloud in a 3D environnement.\r\n3) Install opencv FROM THE GIT REPOSITORY, I advice to you that because I tried doing this installation with an older version of Opencv (that was 3.4.4) downloaded  from the website and it didn't work at the end of the installation, scene_construction wasn't compiled :(. But finally I used the opencv from git and it worked, si follow the step 2 from the instruction \"Clone OpenCV sources: git clone https://github.com/opencv/opencv \u0026\u0026 git clone https://github.com/opencv/opencv_contrib\"\r\n4) Try the step 4, but personally I did that `cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -DBUILD_EXAMPLES=ON -D CMAKE_INSTALL_PREFIX=/usr/local ../opencv` because puting /usr/local prefix means that you install libraries in a default folder, I guess that, I'm not sure ajhajhaj. If it doesn't work , just separate \"-D\" from the next word.\r\n5) If during the building part you have a proble of c++11 missing, go to the cmakefile.txt and add this line `SET(CMAKE_CXX_FLAGS \"-std=c++11 -O3\")` wherever you want.\r\n\r\nI could say that it's ONLY WORKS ON LINUX, one of those libraries only works on linux, I don't remember what library is. SFM scene construction is also posible on windows because there are softwares that works there, but I still don't know how.\r\n\r\nGood luck :)."}],"action":{"name":"View Issue","url":"https://github.com/opencv/opencv_contrib/issues/1924#issuecomment-447662212"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/opencv/opencv_contrib/issues/1924#issuecomment-447662212",
"url": "https://github.com/opencv/opencv_contrib/issues/1924#issuecomment-447662212",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LaurentBerger** [comment]
"I could say that it's ONLY WORKS ON LINUX, one of those libraries only works on linux" [No](https://gist.github.com/LaurentBerger/6a420711d279f73b2eed415b97267df4)
how to build on windows it's [here](https://gist.github.com/LaurentBerger/88da75a01ca715c4fe2bed71fa50ad0f)

**Comment by eliasarellano** [comment]
> "I could say that it's ONLY WORKS ON LINUX, one of those libraries only works on linux" [No](https://gist.github.com/LaurentBerger/6a420711d279f73b2eed415b97267df4)
> how to build on windows it's [here](https://gist.github.com/LaurentBerger/88da75a01ca715c4fe2bed71fa50ad0f)

Thank you ! Sorry if I don't know so much but How do I install that on windows? With CMAKE? Or executing the bash file given by you on windows?, how? It would be REALLY USE FULL because I have to  do an application for windows. 

Regards :).
