### ISSUE TITLE
CUDA CascadeClassifier no longer available

### ISSUE THREAD

**Issue by xsacha** [opencv/opencv_contrib#2048]
This PR (https://github.com/opencv/opencv_contrib/pull/1889) removed objdetect related classes such as cv::cuda::CascadeClassifier. For me, the best part about OpenCV (recently moved to contrib).

The pull request states it is obsolete. If so, what is the replacement? I have not seen anything similar. Please do not suggest DNN as it is far slower and not equivalent at all.

I am still unable to use OpenCV 4.X due to this PR.

**Comment by Ayke** [comment]
+1. Does anyone know any workaround for this?

**Comment by xsacha** [comment]
Does not look like they care about CUDA support anymore. You will have to move on I feel. I already have.

**Comment by Ayke** [comment]
> Does not look like they care about CUDA support anymore. You will have to move on I feel. I already have.

Me too. Have installed OpenCV 3.4, it works fine with CUDA 10.0.

**Comment by c-x-berger** [comment]
Yikes. Can confirm this is still the case for... some reason.

Why this was removed I have no idea, since the PR is nondescript about it. If @alalek would be more specific about what was legacy needing removal I'd happily aim for a patch, but the removed stuff doesn't mention `cvLoad`, which was [apparently what was supposed to be removed?](https://github.com/opencv/opencv_contrib/pull/1889#issuecomment-442735422) Is Open CV [dropping Cascade Classifiers entirely going forward?](https://github.com/opencv/opencv/issues/13231) What's the deal?

You could maybe get away with using the HOG detector? That's still included in 4.1.0. But seeing as the DNN module is slow for you I'm guessing the same applies. (Also, the CUDA HOG `detectMultiScale` needs a `CV_WRAP`, so it's not available from Python.)

**Comment by 06needhamt** [comment]
Are the CPU bound cascade classifiers going to be dropped eventually, as I am planning on using them in the near future?

**Comment by xsacha** [comment]
Probably not as it is easier to maintain

**Comment by 06needhamt** [comment]
Are there any plans to re-add the CUDA classifiers with the new APIs?

**Comment by alalek** [comment]
There are no resources planned for that.
Feel free to prepare patch with migration of disabled code from removed legacy API and validate proposed changes.

**Comment by Raffaello** [comment]
@alalek shouldn't be deprecated and replace with the new one before disabling it?

**Comment by xsacha** [comment]
There is no new one unless someone added one recently

**Comment by nosajthenitram** [comment]
I know this thread is dated at bit at this time, but I've started the effort of getting openCV 4.3.0 to work with cuda cascade classifiers. I have it functioning against simple classifiers, so there's still a little more work to do. I'll push this up to a branch on my work when it's in better shape.

**Comment by 06needhamt** [comment]
Sounds great. Keep us updated on your progress. As I am keen to upgrade to OpenCV 4 but not having CUDA accelerated classifiers is a key blocker.

**Comment by nosajthenitram** [comment]
I've pushed up my first branch with the fix for CUDA cascade classifiers in OpenCV4.x. 

https://github.com/nosajthenitram/opencv_contrib/tree/2048_cuda_cascade_no_longer_available

**Comment by nosajthenitram** [comment]
@alalek Who maintains the xml parser for the persistence module? I've got some questions regarding the cuda cascade classifier xml and how it's consumed. I'm not an xml expert, so I'm not sure what this should look like as it's represented in the file nodes.
