### ISSUE TITLE
error test CV_Face_FacemarkKazemi.can_detect_landmarks

### ISSUE THREAD

**Issue by LaurentBerger** [opencv/opencv_contrib#2153]
test failed with this message : 
[       OK ] CV_Face_FacemarkKazemi.can_loadTrainingData (6837 ms)
[ RUN      ] CV_Face_FacemarkKazemi.can_detect_landmarks
unknown file: error: C++ exception with description "OpenCV(4.1.0-dev) G:\Lib\opencv\modules\ts\src\ts.cpp:992: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: face/face_landmark_model.dat in function 'cvtest::findData'
" thrown in the test body.
[  FAILED  ] CV_Face_FacemarkKazemi.can_detect_landmarks (5 ms)

face_landmark.model.dat should be in opencv_extra/testdata/cv/face but it is not.

Test should be disabled or face_landmark_model.dat add in opencv_extra/testdata/cv/face 

there is this closed issue too #1577

**Comment by alalek** [comment]
This file is [downloaded](https://github.com/opencv/opencv_contrib/blob/04b2f2c5995042a5bbbd7516594bc5d84d09897b/modules/face/CMakeLists.txt#L20) from opencv_3rdparty by CMake.

Testing system supports multiple test data sources (see `findDataFile()`).
Try to run tests from build "root" directory (instead of test project directory like MSVS does).

**Comment by LaurentBerger** [comment]
Ok I understand. I don't set this path so default path is ${build_repo}/testdata
