### ISSUE TITLE
ArUco library possible license incompatibility - ArUco is now GPLv3

### ISSUE THREAD

**Issue by matt6801** [opencv/opencv_contrib#2242]
##### System information (version)

- OpenCV => Any
- Operating System / Platform => Any
- Compiler => Any

##### Detailed description

The ArUco library (https://sourceforge.net/projects/aruco/files/) is licensed per GPLv3 as of at least 2/22/2019.  Does this change render any portions of the OpenCV aruco module GPLed (i.e. incompatible with the OpenCV BSD license)?

##### Steps to reproduce

**Comment by alalek** [comment]
`aruco` module had been added in 2015: #346
Original Aruco version 1.3 is under BSD license (releases in 2017).

License changing of upstream project doesn't impact already existed code in OpenCV.

> GPL

Future updates from latest upstream source code are not possible due license conflict.

**Comment by cyberbeat** [comment]
It seems, that the last version, which is not gpl3 is

https://github.com/LeeXujie/ArUco/tree/master/sources/aruco-3.0.12/src

I tried that library, and its detection is at least 2-3 times faster than the current opencv implementation. I think because the improvements (since version 3) from this paper
https://www.researchgate.net/publication/325787310_Speeded_Up_Detection_of_Squared_Fiducial_Markers
never made it into opencv. It should be evaluated, if it is possible to improve the opencv version in this regard.

**Comment by asmorkalov** [comment]
New Aruco detection algorithm has been merged recently: https://github.com/opencv/opencv_contrib/pull/3151. It's independent implementation and should be faster than version before. It looks like there is no open issues in the ticket. Closed.
