### ISSUE TITLE
updateMotionHistory, calcMotionGradient, calcGlobalOrientation not exposed to python/java

### ISSUE THREAD

**Issue by berak** [opencv/opencv_contrib#230]
they're tagged as CV_EXPORTS_W in optflow/include/opencv2/optflow/motempl.hpp, but don't end up in the python or java wrappers.

this is probably due to a namespace problem, all other code is in `namespace cv::optflow`, the code from motempl.cpp in `namespace cv::motempl`

changing the namespace to `cv::optflow`, too will fix it, but feels like a gross change, hopefully someone has a better idea here.

**Comment by DuinoDu** [comment]
Yes, I come across the same problem when running the python sample "motempl.py" in opencv_contrib/optflow/sample. I need to change "cv2.updateMotionHistory" to "cv2.motempl.updateMotionHistory". I guess this is because this algorithm was once in opencv lib. But I don't know why it is moved to contrib lib. Can anyone give some reasons?

**Comment by berak** [comment]
@DuinoDu , originally, there was a problem with the script generator, it could not handle nested c++ namespaces correctly, so those functions were not available from python at all.

but now this has changed (and this issue can be closed).

you are right, you need to call `cv2.motempl.updateMotionHistory` , thanks for pointing out a flaw in the motempl.py sample, i'll go and fix it later !
