### ISSUE TITLE
Compiling opencv 4.2.0 with contrib 4.2.0

### ISSUE THREAD

**Issue by Shamim1977** [opencv/opencv_contrib#2467]
Compiling opencv 4.2.0 with contrib has become a big trouble for me. 

I followed this tutorial and some other from the net-
https://medium.com/beesightsoft/build-opencv-opencv-contrib-on-windows-2e3b1ca96955

Cmake GUI does create the script and the following command creates my build-
cmake.exe- build . - config Release - target INSTALL

But the problem is, it does not create opencv_world420.dll or opencv_world420d.dll in lib folder. I believe, it misses some more dlls.

Am I missing anything in CMake GUI?

If anybody can suggest a link of OpenCV 4.2.0 compiled with contrib 4.20, it will be a big help too. Btw, I am looking for Win x64 version of it.

Thanks.

**Comment by likecv** [comment]
thanks




| |
likecv
|
|
邮箱：likecv@126.com
|

Signature is customized by Netease Mail Master

On 03/21/2020 13:29, Shamim Hossain wrote:

Compiling opencv 4.2.0 with contrib has become a big trouble for me. 

I followed this tutorial and some other from the net-
https://medium.com/beesightsoft/build-opencv-opencv-contrib-on-windows-2e3b1ca96955

Cmake GUI does create the script and the following command creates my build-
cmake.exe- build . - config Release - target INSTALL

But the problem is, it does not create opencv_world420.dll or opencv_world420d.dll in lib folder. I believe, it misses some more dlls.

Am I missing anything in CMake GUI?

If anybody can suggest a link of OpenCV 4.2.0 compiled with contrib 4.20, it will be a big help too. Btw, I am looking for Win x64 version of it.

Thanks.
