### ISSUE TITLE
Restore LineSegmentDetector LSD & avoid license conflict

### ISSUE THREAD

**Issue by ruelj2** [opencv/opencv_contrib#2524]
Concerning the removal of LSD due to original code license conflict, it would be a great earning for the community to restore it back by modifying the code in order to avoid license conflict.

The original license conflict issue: https://github.com/opencv/opencv_contrib/issues/2016

Proposal:
Find an alternative way to "Compare doubles by relative error" as in original modules/line_descriptor/include/opencv2/line_descriptor/descriptor.hpp between lines 625 and 824.

**Comment by barabanus** [comment]
That would be very useful because LSD line detector is very useful and robust.

**Comment by ruelj2** [comment]
Currently working on it.

**Comment by alalek** [comment]
> Find an alternative way to "Compare doubles by relative error"

This is not enough.
Almost all removed code by mentioned patches has license conflict.

Even derived work from GPL code is not allowed due GPL copyleft license.
Original article should be taken to create code from scratch.

**Comment by ParadoxRobotics** [comment]
As an alternative, I use the original implementation with a python wrapper 
-> https://github.com/xanxys/lsd-python

**Comment by ThadHouse** [comment]
Based on the latest post in https://github.com/opencv/opencv_contrib/issues/2016, it seems like the author of the blog post realized the license issue, and released in a compatible license. Does this mean LineSegmentDetector can be added back into 4.x?

**Comment by alalek** [comment]
Unfortunately problem is much wider than mentioned function which compares floating-point values.
See my comment above from May 10, 2020

**Comment by olimexsmart** [comment]
If someone (I could try) took the time to implement from scratch, then it would be fine?

**Comment by sturkmen72** [comment]
i am happy to annonce that after i send an e-mail to @rafael-grompone-von-gioi he kindly published his [Computation of a NFA related to a binomial distribution code](https://github.com/rafael-grompone-von-gioi/binomial_nfa) with MIT licence. He also states he will be happy to help on restoration of LDS Algorithm in OpenCV.

thank you @rafael-grompone-von-gioi for your great work.

**Comment by olokobayusuf** [comment]
Hey all, I wanted to let you know I've written a [partial implementation of the Line Segment Detector paper](https://github.com/hdkai/Line-Segment-Detector). It works, but unlike the paper, it relies on a density heuristic for filtering lines, instead of the NFA heuristic in the paper. I wasn't able to write a numerically-stable implementation of the NFA function. This is why it's a partial implementation.

@rafael-grompone-von-gioi I hope this can serve as a good launchpad to write a full implementation. I'm more than happy to collaborate on it!

**Comment by olokobayusuf** [comment]
Hey @rafael-grompone-von-gioi , thanks for the quick response. I have inline responses below:

> Thank you for your email.  I’happy to collaborate.  Unfortunately, I will not be able to work on this for about two weeks, I’m overloaded with important work.  So now I just send some short comments.

This is no rush at all. We can get to it whenever you are available.

> I think the NFA validation is core of the LSD method; without that it is not the LSD method.  Without the NFA step is more similar to a variation of Burns et al. method than to LSD.  So I would be happy to help to include the NFA part.

I agree. My implementation was just a quick way to get going, because as I mentioned earlier I wasn't able to compute the NFA.

> I saw you are working on a python implementation.  But, LSD was already in OpenCV before.  Why not using the same implementation and only updating the parts where there were doubts about the license?  This should be minimal work.

My implementation is actually a Cython hybrid, and it has been hand-optimized to run as fast as possible. My understanding was that the OpenCV implementation was completely off limits because of the Affero license, so I had to start from scratch.  I chose to write it in Cython for speed. I'm happy to rewrite the implementation in C++ if needed.

**Comment by sturkmen72** [comment]
> i am happy to annonce that after i send an e-mail to @rafael-grompone-von-gioi he kindly published his [Computation of a NFA related to a binomial distribution code](https://github.com/rafael-grompone-von-gioi/binomial_nfa) with MIT licence. He also states he will be happy to help on restoration of LDS Algorithm in OpenCV.
> 
> thank you @rafael-grompone-von-gioi for your great work.

@alalek can i prepare a patch to revert commits removing LSD and other algos using NFA?

**Comment by alalek** [comment]
@sturkmen72 Sure!
(please update code reference to new repo under MIT license if any)

**Comment by alalek** [comment]
relates https://github.com/opencv/opencv/pull/13942
relates https://github.com/opencv/opencv_contrib/pull/2020

**Comment by sturkmen72** [comment]
https://github.com/opencv/opencv_contrib/pull/3051

**Comment by alalek** [comment]
Restored in 4.5.4 release.

Thanks @sturkmen72 for the efforts!
