### ISSUE TITLE
Ceres 2.0.0 upgrade to C++14 breaks sfm module

### ISSUE THREAD

**Issue by ghfue** [opencv/opencv_contrib#2578]
##### System information (version)
- OpenCV => master
- Operating System / Platform => Ubuntu 18.04
- Compiler => g++ 7.5.0

##### Detailed description

The sfm module does not build with Ceres master (2.0.0) due to Ceres switching to C++14. 

When building OpenCV, it throws an error about `integer_sequence` not being a member of `std`. This is due to `integer_sequence` being added in C++14. 

I was able to build OpenCV with Ceres 2.0.0 by building it with C++14, but I am not confident this is the proper solution for everyone.

The alternative solution would be to stay on Ceres 1.X.X, which could just be documented somewhere.

##### Steps to reproduce

* Build ceres from master (2.0.0 has yet to be tagged)
* Build OpenCV with modules

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by NavneetSajwan** [comment]
Yes, finally someone addressed it. It was driving me mad for months. Is there a workaround until it gets fixed?

**Comment by alalek** [comment]
There is no other way than forcing C++14 compilation mode to compile with new Ceres:
- modern CMake (3.1+) + `cmake -DCMAKE_CXX_STANDARD=14 ...`
- or update CXXFLAGS / CMAKE_CXX_FLAGS / OPENCV_EXTRA_CXX_FLAGS to use C++14

Otherwise we should disable Ceres in OpenCV:
- `cmake -DCMAKE_DISABLE_FIND_PACKAGE_Ceres=ON ...`
- automatic detection of broken compilation can be added later

**Comment by NavneetSajwan** [comment]
If I use an older version of ceres, will SFM work? I am hoping the 1.14.0 version doesn't have this issue. @alalek

**Comment by ghfue** [comment]
@NavneetSajwan I tested yesterday, and everything builds fine with Ceres 1.14.0. The C++14 change was not introduced until 2.0.0.

**Comment by NavneetSajwan** [comment]
Thanks, I confirmed it. No installation errors with ceres 1.4.x . But SFM examples are not built even when `-D BUILD_EXAMPLES=ON`. Did you face the same issue?

**Comment by diablodale** [comment]
FYI, if SFM cmake is updated to c++14, keep in mind that it currently fails its intention on Microsoft compilers. This is due to this following hardcoded option.

https://github.com/opencv/opencv_contrib/blob/bdc01011b02525961417aec2bc3c0fc2c2da5f3a/modules/sfm/CMakeLists.txt#L71

If continuing with the hardcoded approach....Microsoft's `cl.exe` compiler does not support that option in that specific format. You can use a `-` or `/`. You *can not* use an equal sign `=` to separate the option and its value. Microsoft's compiler wants a colon `:`. Also keep in mind that starting with Microsoft VS2017, the default is C++14.

**Comment by NikolausDemmel** [comment]
On macOS, this prevents the ceres-solver formula in Homebrew to be updated to Ceres 2.0.0, since it breaks the opencv formula.

Same issue will be with the rgbd module, which recently acquired a dependency on ceres: #2619

**Comment by wzh4464** [comment]
> If I use an older version of ceres, will SFM work? I am hoping the 1.14.0 version doesn't have this issue. @alalek

How to use old version?
