### ISSUE TITLE
A function call in freetype.cpp causes overflow

### ISSUE THREAD

**Issue by Moldoteck** [opencv/opencv_contrib#2648]
Function is called inside getText method and putOutlineText:       
 FT_Outline_Translate(&outline,
                             cOutlineOffset,
                             cOutlineOffset );

cOutlineOffset is 0x80000000
outline points are in fact of long type. cOutlineOffset by definition is more than long, so if outline has x a positive number, FT_Outline_Translate called with cOutlineOffset will cause overflow for type long and will generate negative numbers. In fact, i think that this function call is not needed at all, but removing it would imply changing other parts of the code. For what purpose it serves?

P.S. the reason for this error is that
For 64-bit systems, the primary **Unix** 'de facto' standard is LP64 — **long and pointer are 64-bit** (but int is 32-bit). The **Windows** 64-bit standard is LLP64 — long long and pointer are 64-bit (**but long and int are both 32-bit)**. 

For Linux system it will work ok, but for Windows, cOutlineOffset will cause overflow

**Comment by Kumataro** [comment]
Thank you for reporting.I wrote this module in 4 years ago. In currently I forget why this workaround  needed. I can't answer clearly immediate.

 It seems to be an interface mismatch between FreeType and this module. I'll investigate it more in this weekend.

definition
 - Canvas :  destination opencv mat image to draw glyph.

I think cOutlineOffset  is introduced to workaround to get boundary box of text string which has glyph across some edge of canvas correctly. 

When drawing glyph as outline, sometimes any outline-points are located in out-side of canvas. But FreeType library handles points as FT_Vector(in this case 26.6 Fixed-real). To resolve difference of those unit, it was introduced.

But it workaround is used to getTextSize() only, not to draw it. So i believe there are more better method. So I think it is needed to investigate

**Comment by Moldoteck** [comment]
> Thank you for reporting.I wrote this module in 4 years ago. In currently I forget why this workaround needed. I can't answer clearly immediate.
> 
> It seems to be an interface mismatch between FreeType and this module. I'll investigate it more in this weekend.
> 
> definition
> 
> * Canvas :  destination opencv mat image to draw glyph.
> 
> I think cOutlineOffset is introduced to workaround to get boundary box of text string which has glyph across some edge of canvas correctly.
> 
> When drawing glyph as outline, sometimes any outline-points are located in out-side of canvas. But FreeType library handles points as FT_Vector(in this case 26.6 Fixed-real). To resolve difference of those unit, it was introduced.
> 
> But it workaround is used to getTextSize() only, not to draw it. So i believe there are more better method. So I think it is needed to investigate

Well, i made some changes and deleted that constant and now it works +- as expected(sometimes it fails by 1 pixel), but since the code is too messy i will make a commit/ pull request when i'll make it a little better, maybe in the weekend + i'll add some comments im the code so that it will be more understandable. I'll keep you in touch

**Comment by Kumataro** [comment]
Thank you , and sorry for waiting... This is brief report.

After I read code again, I notice that this offset parameter is used in callback function to determine position in cv::Mat too. 

- OpenCV handlles it in [INT_MIN, INT_MAX]. (Point)
- FreeType handles it in [0, UINT_MAX / 64 ) (FT_Vector)

putText function requests `Point org` as strings origin position.
```
    void putText(
        InputOutputArray img, const String& text, Point org,
        int fontHeight, Scalar color,
        int thickness, int line_type, bool bottomLeftOrigin
```

For example user apps can request to draw any strings from out position of canvas. The points of glyph are located in [INT_MIN, 0).  Those points cannot express in FT_Vector completely.

One of solution  is moving temporary the origin in FT_Vector from (0,0) to ( (UINT_MAX/32)/2, (UINT_MAX/32)/2 ) is usable in almost cases. However this current coding without any range-check and convertion-check maybe have some bug.  

Maybe it is better to fix it with other method instead of removing this parameter simply, and I will investigate.

**Comment by Kumataro** [comment]
Thank you very much ! I had misunderstandings. 

[Result]
- It is safe to remove cOutlineOffset at all. This parameter is not useful with FreeType 2.10.
- I am considering fixing the Outline drawing/getTextSize processing to be completed within the FreeType2 coordinate system.
- https://github.com/Kumataro/opencv_contrib/commit/39ffff662d0a19293f20f2f7b18cfc6b701aad9c

[Detail]
The FreeType2 documentation notes that FT_Pos is treated as a 26.6 fixed decimal format in Outline processing (though neither explicitly signed nor unsigned is specified).

-https://www.freetype.org/freetype2/docs/reference/ft2-glyph_management.html#ft_outlineglyphrec
-https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#ft_pos

For that reason, I assumed that the negative value cannot be handled on the coordinates because the outline processing is performed as "unsigned". I introduced cOutlineOffset so that all the points in FreeType coordinates were processed with only positive numbers.

However, this assumption was incorrect. I tried with FreeType library 2.10.1-2, and when I set the drawing position outside the destination image, FreeType Library returned the value of negative coordinates(as 26.6 fixed decimal format).

So I referred to the FreeType 2 documentation again. So I discovered **FT26dot6**. This variable type is "signed" 26.6 fixed decimal format.

-https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#ft_f26dot6

If the FreeType2 library handles 26.6 fixed decimals as "signed" 26.6 fixed decimals, naturally it can also handle negative coordinate systems. So there is no need to use cOutlineOffset in this module.

[Next]
In response to this, I consider whether the outline process (and getTextSize process) using  FreeType2 module can be calculated by the coordinate of FreeType2 only. 

https://github.com/Kumataro/opencv_contrib/commit/39ffff662d0a19293f20f2f7b18cfc6b701aad9c

I believe this method can solve potential integer/long/pointer problems.

**Comment by Moldoteck** [comment]
@Kumataro i have tested your changes for my use-case and it works pretty great. Thank you for this fix!
Can you make a pull request?

**Comment by Kumataro** [comment]
Thank you very much for your help in this issue.

I visually checked the output images with sample sentences in English and Japanese using 59 fonts with different thicknesses and typefaces. I confirmed that there was no new problem after code fix.

* M+ has 43 fonts.
* Noto Serif CJK has 7 fonts
* Noto Sans CJK has 9 fonts

I created Pull Request #2684 . Thank you again!

**Comment by Moldoteck** [comment]
thank you too for fixing this bug

**Comment by Moldoteck** [comment]
Solved: https://github.com/opencv/opencv_contrib/pull/2684
