### ISSUE TITLE
Bug in inpaint_fsr function for 16 bits / 32 bits / 64 bits images

### ISSUE THREAD

**Issue by ferreram** [opencv/opencv_contrib#2855]
##### System information (version)
- OpenCV => 4.5
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC
- 
##### Detailed description

When calling inpaint function from xphoto module with INPAINT_FSR_(BEST/FAST) parameter, there is an OpenCV exception if the provided src image is different than CV_8U.

This behavior is due to the call to : "src.convertTo(src, CV_8U, 1/257.0)" whereas src is a const reference argument.

##### Steps to reproduce

```cpp
#include <opencv2/xphoto/inpainting.hpp>

int main()
{
    cv::Mat input_16U_img = cv::Mat::zeros(cv::Size(500,500), CV_16U);
    cv::Mat mask = cv::Mat::zeros(input_16U_img.size(), CV_8U);
    cv::Mat out_img;
    cv::xphoto::inpaint(input_16U_img, mask, out_img, cv::xphoto::INPAINT_FSR_FAST);

    return 0;
}
```

**Comment by alalek** [comment]
Please provide complete minimal reproducer as requested by issue's template.

**Comment by berak** [comment]
imo, this issue is still valid.
[here](https://github.com/opencv/opencv_contrib/blob/d85887cd8bf2fb567c96632dea1caedd50316995/modules/xphoto/src/inpainting_fsr.impl.hpp#L770) and [here](https://github.com/opencv/opencv_contrib/blob/d85887cd8bf2fb567c96632dea1caedd50316995/modules/xphoto/src/inpainting_fsr.impl.hpp#L785) src is const, but the code tries to convert it in-place, resulting in:

```
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.6.0-dev) Error: Assertion failed (!fixedType() || ((Mat*)obj)->type() == mtype) in create, file C:\p\opencv\modules\core\src\matrix_wrap.cpp, line 1166
```

**Comment by 3jbrown** [comment]
I agree this issue should be re-opened! I can reproduce in c++ or python. INPAINT_FSR_BEST/FAST only work with uint8, nothing larger.
