### ISSUE TITLE
cuda::HoughSegmentDetector: macro to ignore stream should have been removed in #2801

### ISSUE THREAD

**Issue by deadprogram** [opencv/opencv_contrib#3015]
We ran into a problem with trying to use mutiple `cuda::HoughSegmentDetector` each with their own non-default async `cuda::Stream`. On looking into the code, it seems like the macro `CV_UNUSED(stream);` should have been removed in that PR #2801 but was perhaps missed?

https://github.com/opencv/opencv_contrib/blob/907efb966823ea3ca40b70500068866f6bfb8f3a/modules/cudaimgproc/src/hough_segments.cpp#L146

Not sure if this is actually to do with our error, listed here:

```
what():  OpenCV(4.5.3) /opencv_contrib-4.5.3/modules/cudaimgproc/src/cuda/hough_segments.cu:234: error: (-217:Gpu API call) an illegal memory access was encountered in function 'houghLinesProbabilistic_gpu'
```

However it certainly seems like something that should be addressed, right? Thanks.

**Comment by alalek** [comment]
`CV_UNUSED(stream)` is "no op" statement to avoid compiler warnings.
It can't cause any runtime errors.

---

Please provide complete minimal reproducer (including of input data).
Provide system specification which cause this error.

**Comment by mitul93** [comment]
Hi @alalek 

Here are the details

OpenCV version : 4.5.3
opencv-contrib version : 4.5.3
OS : Ubuntu 18.04.1
CUDA version : 11.2
GPU : Quadro RTX 4000

Here is the problematic test case [hough_test_case.zip.gz](https://github.com/opencv/opencv_contrib/files/7000889/hough_test_case.zip.gz)

The crash is random in nature. You may need to run it two or three times to see the crash as reported in the logs below.

The logs 
`root@df29f8235b3a:/src/testdata# ./hough_crash_reproduce 
Test case for hough segmentation cuda crash...
Reading test image...
Test image reading successful.
Thread, 4, index, 0,Found #lines, 4096
Thread, 3, index, 0,Found #lines, 4096
Thread, 1, index, 0,Found #lines, 4096
Thread, 0, index, 0,Found #lines, 4096
Thread, 1, index, 1,Found #lines, 4096
Thread, 4, index, 1,Found #lines, 4096
Thread, 2, index, 0,Found #lines, 4096
Thread, 3, index, 1,Found #lines, 4096
Thread, 4, index, 2,Found #lines, 4096
Thread, 1, index, 2,Found #lines, 4096
Thread, 0, index, 1,Found #lines, 4096
Thread, 3, index, 2,Found #lines, 4096
Thread, 0, index, 2,Found #lines, 4096
Thread, 3, index, 3,Found #lines, 4096
Thread, 0, index, 3,Found #lines, 4096
Thread, 3, index, 4,Found #lines, 4096
Thread, 0, index, 4,Found #lines, 4096
Thread, 3, index, 5,Found #lines, 4096
Thread, 1, index, 3,Found #lines, 4096
Thread, 2, index, 1,Found #lines, 4096
Thread, 3, index, 6,Found #lines, 4096
Thread, 0, index, 5,Found #lines, 4096
Thread, 0, index, 6,Found #lines, 4096
Thread, 3, index, 7,Found #lines, 4096
Thread, 0, index, 7,Found #lines, 4096
Thread, 3, index, 8,Found #lines, 4096
Thread, 0, index, 8,Found #lines, 4096
Thread, 3, index, 9,Found #lines, 4096
Thread, 0, index, 9,Found #lines, 4096
Thread, 2, index, 2,Found #lines, 4096
Thread, 0, index, 10,Found #lines, 4096
Thread, 4, index, 3,Found #lines, 4096
Thread, 3, index, 10,Found #lines, 4096
Thread, 2, index, 3,Found #lines, 4096
Thread, 3, index, 11,Found #lines, 4096
Thread, 0, index, 11,Found #lines, 4096
Thread, 2, index, 4,Found #lines, 4096
Thread, 1, index, 4,Found #lines, 4096
Thread, 0, index, 12,Found #lines, 4096
Thread, 4, index, 4,Found #lines, 4096
Thread, 3, index, 12,Found #lines, 4096
Thread, 2, index, 5,Found #lines, 4096
Thread, 1, index, 5,Found #lines, 4096
Thread, 0, index, 13,Found #lines, 4096
Thread, 4, index, 5,Found #lines, 4096
Thread, 3, index, 13,Found #lines, 4096
Thread, 2, index, 6,Found #lines, 4096
Thread, 1, index, 6,Found #lines, 4096
Thread, 0, index, 14,Found #lines, 4096
Thread, 3, index, 14,Found #lines, 4096
Thread, 4, index, 6,Found #lines, 4096
Thread, 2, index, 7,Found #lines, 4096
Thread, 1, index, 7,Found #lines, 4096
Thread, 3, index, 15,Found #lines, 4096
Thread, 0, index, 15,Found #lines, 4096
Thread, 4, index, 7,Found #lines, 4096
Thread, 1, index, 8,Found #lines, 4096
Thread, 0, index, 16,Found #lines, 4096
Thread, 2, index, 8,Found #lines, 4096
Thread, 4, index, 8,Found #lines, 4096
Thread, 3, index, 16,Found #lines, 4096
Thread, 1, index, 9,Found #lines, 4096
Thread, 4, index, 9,Found #lines, 4096
Thread, 0, index, 17,Found #lines, 4096
Thread, 2, index, 9,Found #lines, 4096
Thread, 3, index, 17,Found #lines, 4096
Thread, 1, index, 10,Found #lines, 4096
Thread, 4, index, 10,Found #lines, 4096
Thread, 2, index, 10,Found #lines, 4096
Thread, 3, index, 18,Found #lines, 4096
Thread, 0, index, 18,Found #lines, 4096
Thread, 1, index, 11,Found #lines, 4096
Thread, 4, index, 11,Found #lines, 4096
Thread, 2, index, 11,Found #lines, 4096
Thread, 3, index, 19,Found #lines, 4096
Thread, 1, index, 12,Found #lines, 4096
Thread, 0, index, 19,Found #lines, 4096
Thread, 4, index, 12,Found #lines, 4096
Thread, 2, index, 12,Found #lines, 4096
Thread, 3, index, 20,Found #lines, 4096
Thread, 2, index, 13,Found #lines, 4096
Thread, 3, index, 21,Found #lines, 4096
Thread, 1, index, 13,Found #lines, 4096
Thread, 2, index, 14,Found #lines, 4096
Thread, 0, index, 20,Found #lines, 4096
Thread, 4, index, 13,Found #lines, 4096
Thread, 3, index, 22,Found #lines, 4096
Thread, 4, index, 14,Found #lines, 4096
Thread, 1, index, 14,Found #lines, 4096
Thread, 2, index, 15,Found #lines, 4096
Thread, 0, index, 21,Found #lines, 4096
Thread, 3, index, 23,Found #lines, 4096
Thread, 0, index, 22,Found #lines, 4096
Thread, 1, index, 15,Found #lines, 4096
Thread, 2, index, 16,Found #lines, 4096
Thread, 0, index, 23,Found #lines, 4096
Thread, 1, index, 16,Found #lines, 4096
Thread, 0, index, 24,Found #lines, 4096
Thread, 3, index, 24,Found #lines, 4096
Thread, 1, index, 17,Found #lines, 4096
Thread, 0, index, 25,Found #lines, 4096
Thread, 4, index, 15,Found #lines, 4096
Thread, 2, index, 17,Found #lines, 4096
Thread, 3, index, 25,Found #lines, 4096
Thread, 1, index, 18,Found #lines, 4096
Thread, 0, index, 26,Found #lines, 4096
Thread, 2, index, 18,Found #lines, 4096
Thread, 4, index, 16,Found #lines, 4096
Thread, 3, index, 26,Found #lines, 4096
Thread, 1, index, 19,Found #lines, 4096
Thread, 0, index, 27,Found #lines, 4096
Thread, 4, index, 17,Found #lines, 4096
Thread, 3, index, 27,Found #lines, 4096
Thread, 4, index, 18,Found #lines, 4096
Thread, 1, index, 20,Found #lines, 4096
Thread, 0, index, 28,Found #lines, 4096
Thread, 3, index, 28,Found #lines, 4096
Thread, 2, index, 19,Found #lines, 4096
Thread, 4, index, 19,Found #lines, 4096
Thread, 3, index, 29,Found #lines, 4096
Thread, 0, index, 29,Found #lines, 4096
Thread, 1, index, 21,Found #lines, 4096
Thread, 2, index, 20,Found #lines, 4096
Thread, 3, index, 30,Found #lines, 4096
Thread, 0, index, 30,Found #lines, 4096
Thread, 4, index, 20,Found #lines, 4096
Thread, 1, index, 22,Found #lines, 4096
Thread, 3, index, 31,Found #lines, 4096
Thread, 0, index, 31,Found #lines, 4096
Thread, 4, index, 21,Found #lines, 4096
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.3) /opencv_contrib-4.5.3/modules/cudaimgproc/src/cuda/hough_segments.cu:234: error: (-217:Gpu API call) an illegal memory access was encountered in function 'houghLinesProbabilistic_gpu'
terminate called recursively

terminate called recursively
Aborted (core dumped)`

I have applied following path inspired from [#6742](https://github.com/opencv/opencv/issues/6742). That stopped the crash and the same code reports the same no of hough lines.

Here's the patch

`52c52
<         texture<uchar, cudaTextureType2D, cudaReadModeElementType> tex_mask(false, cudaFilterModePoint, cudaAddressModeClamp);
---
>         //texture<uchar, cudaTextureType2D, cudaReadModeElementType> tex_mask(false, cudaFilterModePoint, cudaAddressModeClamp);
59c59
<                                                 int* counterPtr)
---
>                                                 int* counterPtr, PtrStepSzb mask)
160c160,161
<                     if (tex2D(tex_mask, p1.x, p1.y))
---
>                     //if (tex2D(tex_mask, p1.x, p1.y))
>                     if(mask(p1.x, p1.y))
219a221,222
>             PtrStepSzb dat(mask);
> 
223c226
<             bindTexture(&tex_mask, mask);
---
>             //bindTexture(&tex_mask, mask);
230c233
<                                                      counterPtr);
---
>                                                      counterPtr, dat);`

Please will you verify if 
1. The problem is not because of how we use cv::cuda calls in multi-thread code
2. The patch is a good solution for the problem

Thanks
MV

**Comment by deadprogram** [comment]
Closing as we will open new issue with correct description of problem and then PR with our solution.
