### ISSUE TITLE
Relax the restriction of 3-channel

### ISSUE THREAD

**Issue by volezheng** [opencv/opencv_contrib#3276]
https://github.com/opencv/opencv_contrib/blob/98f6a2e55453fdb109d18403ed546ac9d72161b4/modules/freetype/src/freetype.cpp#L197

With the restriction, it's not allowed to put text on grayscale text directly.

```
img = np.zeros((full, full), dtype=np.uint8)
# ft.putText(img, char, textOrg, height, 255,
#            thickness, 8, bottomLeftOrigin=True)
cv.putText(img, 'l', textOrg, cv.FONT_HERSHEY_SIMPLEX, 0.3, 255)  # this works
```

The ft version fails with:
`cv2.error: OpenCV(4.4.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-7r9u7hyj/opencv_contrib/modules/freetype/src/freetype.cpp:196: error: (-215:Assertion failed) ( _img.empty() == false ) && ( _img.isMat() == true ) && ( _img.depth() == CV_8U ) && ( _img.dims() == 2 ) && ( _img.channels() == 3 ) in function 'putText'`

**Comment by Kumataro** [comment]
(This issue is about freetype wrapper module.)
Thank you your report.

## Limitation

As first, The API of putText() in freetype wrapper module is based on ( or similar to ) imgprocs's putText(). But there are no compatibility.
  
And limitatation, which a destination cv::Mat should be 8UC3, is descripted in OpenCV 4.5.1 document(and more newer) clealy.

## Drawing modes.

There are 3 drawing modes in freetype wrapper module.

1) drawing-mono-bitmaps (simply pixel copy)
2) drawing-blend-bitmaps (alpha blending)
3) drawing-outline-paths.

### For outline-paths

I think to support drawing-outline-paths on 1 channel cv::Mat is not difficult, because it use path-drawing function in imgproc module.

### For bitmap (mono and blend) bitmaps

Both drawing-mono-bitmaps or drawing-blend-bitmaps do not use this function, freetype module draw glyph pixels in the cv::Mat directly. So it makes harder to expand support channel from fixed-RGB to Gray or CMYK.

I think drawing on a 1-channel image can be realized by simply duplicating the existing RGB code and modifying it for Gray. 

But to keep the maintainability of the source code, I believe it is not good way. It seems difficult to give a good answer immediately. I'm sorry.
