### ISSUE TITLE
A problem about kcf_tracker init function

### ISSUE THREAD

**Issue by honggang0524** [opencv/opencv_contrib#3345]
- OpenCV =3.4.16
- Operating System / Platform = Ubuntu20
- Compiler => Visual Studio 

For the same tracker, can the init function be executed again after the update function returns fasle? Or do you need to release this tracker and recreate a new tracker?

**Comment by berak** [comment]
> For the same tracker, can the init function be executed again after the update function returns fasle? Or do you need to release this tracker and recreate a new tracker?

no, you cannot reuse the instance and call init() on it again, you need to create a new one each time, update() fails.

(that's why the interfaces were refactored in 4.x, and all classes, where this behaviour could not be changed, were put into a `legacy` namespace.)

however, this is the library bug tracker, in the future, please ask questions like this on https://forum.opencv.org/ , thank you.

**Comment by alalek** [comment]
> no, you cannot reuse the instance and call init() on it again

This is not accurate.
Modern Tracker API allows to do that.
See sample code: https://github.com/opencv/opencv/blob/4.6.0/samples/python/tracker.py#L68

Tracker's instance recreation should be avoided due to overhead, which may be huge in some cases - e.g. loading of DNN models (see GOTURN tracker).
