### ISSUE TITLE
xobjdetect  changged?

### ISSUE THREAD

**Issue by hellozjr** [opencv/opencv_contrib#507]
hello, i want to know some message about ICF/ACF,i remember xobjdetect have interface like ICFDetector,but  i can't find any message about it in this version now.

**Comment by hellozjr** [comment]
under the opencv_contrib\modules\xobjdetect ,i can't find any message about ICF.....somebody knows? thanks.

**Comment by teng88** [comment]
the author has delete all ICF related code in the newest version

**Comment by StevenPuttemans** [comment]
https://github.com/Itseez/opencv_contrib/pull/291 As you can see in this PR the contributed content was indeed deleted without prior notice. So my guess is
1) it either got deleted because of the crappy performance compared to the original matlab code
2) or the author sold his code to someone, not finishing it in OpenCV and removing it here

There are several other C++ implementations out there, as cited [here](http://answers.opencv.org/question/83904/train-a-classifier-to-detect-objects-based-on-its-form-and-colors)

**Comment by StevenPuttemans** [comment]
BTW maybe some of us can work together of getting an existing C++ ACF/ICF framework integrated?
