### ISSUE TITLE
Support SFM on Windows!

### ISSUE THREAD

**Issue by AGPX** [opencv/opencv_contrib#573]
Hello, there's a way to compile the module SFM for Windows? The docs state "the sfm module is only available in Linux.", however all the dependencies are available and can be compiled on Windows. In addition, somebody had success in compiling such module on Windows (http://qiita.com/SatoshiRobatoFujimoto/items/c87b14cd20cda3c97306).
Can you please fix this? Thank you so much.

**Comment by PhilLab** [comment]
:+1:

**Comment by LaurentBerger** [comment]
Have you installed sfm on windows ?

**Comment by alalek** [comment]
Should be fixed in #789

**Comment by LaurentBerger** [comment]
So something must be wrong in my installed :

Caffe: NO
Protobuf: NO
Glog: NO
Found required Ceres dependency: Eigen version 3.3.0 in F:/lib/eigen-eigen
No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
Found installed version of glog: F:/lib/glog
Detected glog version: 0.3.4
Found required Ceres dependency: Glog in
Found Ceres version: 1.12.0 installed in: C:/Program Files/Ceres with components: [SchurSpecializations, OpenMP]
Checking SFM deps... TRUE
Module opencv_sfm disabled because the following dependencies are not found: Eigen

**Comment by LaurentBerger** [comment]
I have deleted cmake cahe and used cmake GUI 3.7.0.rc2. 
1 press configure in GUI
2 give OPENCV_EXTRA_MODULES_PATH
3 configure. result is Checking SFM deps... TRUE
Module opencv_sfm disabled because the following dependencies are not found: Eigen
variable EIGEN_INCLUDE_PATH-NOTFOUND (but EIGEN_INCLUDE_DIR is good)
4 Manually I set EIGEN_INCLUDE_PATH to  EIGEN_INCLUDE_DIR 
and not BUILD_opencv_sfm is true

**Comment by LaurentBerger** [comment]
Then build on windows 10 with VS 2015 is not possible for multiview project M_PI is undefined. Preprocessor definition _USE_MATH_DEFINES can be add

**Comment by terfendail** [comment]
@LaurentBerger  It looks like OpenCV still consider there is no Eigen and doesn't update `HAVE_EIGEN` variable value even if Eigen is found. When I tried to make SFM for Windows I set `WITH_EIGEN` flag during configuration. So may be it could help to detect Eigen the way it would be suitable for SFM.
