### ISSUE TITLE
Tracking TLD: Greyscale Image bug

### ISSUE THREAD

**Issue by api55** [opencv/opencv_contrib#625]
I am using the Tracking Module with the TLD variant. When I pass a greyscale image (CV_8U) it gives an assertion error:

`openCV Error: Assertion failed (scn == 3 || scn == 4)`

That means it is trying to convert the image from RGB (CV_8UC3) to greyscale...

I think that it should be able to detect that is CV_8U and avoid this step.

Or does the algorithm needs to have RGB images for another reason?

**Comment by StevenPuttemans** [comment]
The conversion happens at initialization for TLD tracker right [here](https://github.com/Itseez/opencv_contrib/blob/master/modules/tracking/src/tldTracker.cpp#L85). Since it starts with conversion at initialization phase it is no longer needed to have a colour image.

This function is called from the [tracker initialization](https://github.com/Itseez/opencv_contrib/blob/master/modules/tracking/src/tracker.cpp#L76) but since there might be trackers using color information, I suggest adapting the specific initializer from

`cvtColor( image, image_gray, COLOR_BGR2GRAY );`

to

```
switch( image.channels() ){
   case: 3
      cvtColor( image, image_gray, COLOR_BGR2GRAY );
      break;
   default:
      image_gray = image.clone();
}
```

Could you supply a [PR](https://github.com/Itseez/opencv/wiki/How_to_contribute) with the fix or suggest another one?

**Comment by api55** [comment]
That is exactly what I was thinking, I will supply the pull request as soon as I get to my pc. I will also change the the update function a couple of lines below the one you linked, exactly ([here](https://github.com/Itseez/opencv_contrib/blob/master/modules/tracking/src/tldTracker.cpp#L110)). 

Thanks for the help

**Comment by StevenPuttemans** [comment]
You are welcome! Thanks for the updates!
