### ISSUE TITLE
DNN module, old style .prototxt file parser

### ISSUE THREAD

**Issue by CrazyBaran** [opencv/opencv_contrib#658]
When try use dnn::createCaffeImporter with .prototxt file, where input layer is declare as
 `name: "CaffeNet"
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 1 dim: 3 dim: 64 dim: 64 } }
}`
throw a exception about input_param. Walk around this problem is change this to 
`name: "CaffeNet"
input: "data"
input_dim: 1 
input_dim: 3 
input_dim: 64 
input_dim: 64`, but this make problem with developing caffe in openCV. I think some change goes in caffe.proto.

**Comment by ludv1x** [comment]
Hello, @CrazyBaran 
Can you get link to provided .prototxt?
It's very strange, since GoogleNet works fine with similar shape declaration:
> name: "GoogleNet"
> layer {
>   name: "data"
>   type: "Input"
>   top: "data"
>   input_param { shape: { dim: 10 dim: 3 dim: 224 dim: 224 } }
> }
> 

BTW, Top-level `input_dim` fields (and even `input`) can be painlessly removed.
They are redundant since you set shape of net input making `net.setBlob(".data", inputBlob);`
