### ISSUE TITLE
vector of vectors (InputArrayOfArrays) mapped to Java's List<Mat> correct?

### ISSUE THREAD

**Issue by dharezlak** [opencv/opencv_contrib#706]
Is there a way to properly build a `Mat` object in Java so it is converted to a vector in C++? Such mapping is done in the `decode` method of the `structured_light` module. More naturally the vector of vectors should be mapped to `List<List<Mat>>`.

This was also posted as an OpenCV question at http://answers.opencv.org/question/96672/how-to-map-javas-listmat-to-vector-of-vectors.

**Comment by rnamdos** [comment]
Hi @komakai @RobertaRavanelli 

Thank you for your work. I have a similar question as I have problems inputting the `patternImages` into the `cv2.structured_light_StructuredLightPattern.decode` function in python. 

The documentation states that patternImages is a `vector<vector<Mat>>`
`retval, disparityMap = cv.structured_light_StructuredLightPattern.decode(patternImages[, disparityMap[, blackImages[, whiteImages[, flags]]]])`

I tried a 2D list/nparray for the images but I receive a type error:
`TypeError: descriptor 'decode' requires a 'cv2.structured_light_StructuredLightPattern' object but received a 'numpy.ndarray'`

What is the proper type for the patternImages object?

**Comment by komakai** [comment]
@rnamdos I am building OpenCV with Python bindings enabled and saw the following output:

SKIP:bool cv::structured_light::StructuredLightPattern::decode(vector_vector_Mat patternImages, Mat& disparityMap, vector_Mat blackImages = vector_Mat(), vector_Mat whiteImages = vector_Mat(), int flags = DECODE_3D_UNDERWORLD)	 due to ARG type vector_vector_Mat/I

The Objective-C/Swift binding for this function however is working fine

**Comment by DuncanM-XR** [comment]
@rnamdos Did you resolve this error in the python version of the function? I have had this error appear in a project I'm working on too.

**Comment by rnamdos** [comment]
@DuncanM-XR it was a noob mistake I made because I was still learning python. The code is fine, make sure you are referencing the class properly. I was able to get the code working with the sample images and got the point cloud, however after messing around for many weeks, i wasn't able to get it to create point clouds from my setup. If there was a python code maybe more people could actually verify its operation beyond 3D modeling a flat wall! Good luck!

**Comment by teshaTe** [comment]
@rnamdos it looks like that you have figured out how to run the decode method. 

cv2.structured_light_GrayCodePattern.decode(images, blackImages=black_images, 
                                                                          whiteImages=white_images,
                                                                          flags=cv2.structured_light.DECODE_3D_UNDERWORLD)
                                                                          
May be you can help to figure out what data type should be 'images'. I have tried this one: 

images = np.array([np.array(images_right), np.array(images_left)]), 

where each element of the 'images_right' and 'images_left' is an numpy.ndarray (images uploaded using cv2.imread()). Same for the 'black_images' and 'white_images'. The decode function complains that it does not work with ndarrays.

The error itself:

Traceback (most recent call last):
  File "D:/M__XR/PyCharm/StructuredLight/project/tools/OpenCVStructLight.py", line 77, in <module>
    ret, disparityMap = cv2.structured_light_GrayCodePattern.decode(images, blackImages=black_images,
TypeError: descriptor 'decode' for 'cv2.structured_light_StructuredLightPattern' objects doesn't apply to a 'numpy.ndarray' object

**Comment by alalek** [comment]
> cv2.structured_light_GrayCodePattern.decode(images, ...

@teshaTe Methods should be applied with corresponding class instance. They should not be called as a function.

**Comment by teshaTe** [comment]
Ah, some stupid mistake of mine. I am still  new with python. Thank you @alalek  for pointing it out.
