### ISSUE TITLE
cv::aruco::estimatePoseBoard returns nonsensical values

### ISSUE THREAD

**Issue by ekuznetsov139** [opencv/opencv_contrib#744]
I'm using cv::aruco to do global camera position tracking in a video. Most of the time it works as expected. However, on some occasions (seems to be happening only if all visible markers are coplanar, and mainly if there are only two of them within the field of view), rvec/tvec values returned by estimatePoseBoard jump from correct values to a completely different corner of the parameter space. Upon close examination, it appears that returned values are technically correct, but correspond to a transformation where all visible markers on the board are behind the camera (if I apply specified rotation and translation to elements of Board::objPoints, all resulting Point3f's have negative z-components). I sincerely doubt that this is the intended behavior.

This could be ameliorated to a degree by passing known good recent rvec/tvec to solvePnP as hints inside estimatePoseBoard (since solvePnP iterates to the correct transformation most of the time when given a good hint), but current API does not have this functionality.

I can provide sample input values that trigger this behavior. I've observed this in official 3.1.0 but I don't see any changes in git that would have fixed this. (estimatePoseBoard in particular is very short, and there weren't many changes to the implementation of solvePnP.)

**Comment by savuor** [comment]
@ekuznetsov139 could you please provide a sample code to reproduce the bug and give some additional info?

**Comment by ekuznetsov139** [comment]
Try to run this

`
void doArucoGlitch()
{
	double matrixData[9] = { -3.9062571886921410e+02, 0., 4.2350000000000000e+02,
		0., 3.9062571886921410e+02, 2.3950000000000000e+02, 0., 0., 1 };
	cv::Mat cameraMatrix = cv::Mat(3, 3, CV_64F, matrixData);

	cv::aruco::Board board;
	board.ids = vector < int > {0, 1};
	board.objPoints.resize(2);
	board.objPoints[0] = { { 0.326198f, -0.030621f, 0.303620f }, { 0.325340f, -0.100594f, 0.301862f }, { 0.255859f, -0.099530f, 0.293416f }, { 0.256717f, -0.029557f, 0.295174f }, };
	board.objPoints[1] = { { -0.033144f, -0.034819f, 0.245216f }, { -0.035507f, -0.104705f, 0.241987f }, { -0.105289f, -0.102120f, 0.237120f }, { -0.102926f, -0.032235f, 0.240349f }, };

	vector<int> ids = { 0, 1 };
	vector<vector<Point2f> > corners;
	corners.resize(2);
	corners[0] = { { 37.7f, 203.3f }, { 38.5f, 120.5f }, { 105.5f, 115.8f }, { 104.2f, 202.7f }, };
	corners[1] = { { 476.0f, 184.2f }, { 479.6f, 73.8f }, { 590.9f, 77.0f }, { 587.5f, 188.1f }, };

	Vec3d rvec, tvec;
	int nUsed = cv::aruco::estimatePoseBoard(corners, ids, board, cameraMatrix, Mat(), rvec, tvec);
	printf("Calculated transform: %f %f %f   %f %f %f (used %d markers)\n", rvec[0], rvec[1], rvec[2], tvec[0], tvec[1], tvec[2], nUsed);
	vector<Point2f> projected;
	cv::projectPoints(board.objPoints[0], rvec, tvec, cameraMatrix, Mat(), projected);
	printf("Projected point: %f %f\n", projected[0].x, projected[0].y);
	printf("\n\n");

	corners[0] = { { 38.4f, 204.5f }, { 40.0f, 124.7f }, { 102.0f, 119.1f }, { 99.9f, 203.6f } };
	corners[1] = { { 476.0f, 184.3f }, { 479.2f, 75.1f }, { 588.7f, 79.2f }, { 586.3f, 188.5f } };

	nUsed = cv::aruco::estimatePoseBoard(corners, ids, board, cameraMatrix, Mat(), rvec, tvec);
	printf("Calculated transform: %f %f %f   %f %f %f (used %d markers)\n", rvec[0], rvec[1], rvec[2], tvec[0], tvec[1], tvec[2], nUsed);
	cv::projectPoints(board.objPoints[0], rvec, tvec, cameraMatrix, Mat(), projected);
	printf("Projected point: %f %f\n", projected[0].x, projected[0].y);
	printf("\n\n");
}
`

I'm getting:

Calculated transform: -0.030895 -0.043628 -0.004032   0.011177 -0.007931 0.007206 (used 2 markers)
Projected point: 35.134155 203.231842


Calculated transform: -0.542785 -0.023275 3.101528   0.085977 0.004038 -0.502647 (used 2 markers)
Projected point: 36.781155 205.636002

Note that corner locations are almost identical (differ by a couple of pixels at most) but rvec/tvec values are drastically different. If you add code to calculate marker coordinates after transform but before projection, you'll see that the first transform corresponds to a valid solution (markers in front of the camera. z-components positive, on the order of 0.33), and the second transform is spurious (markers behind the camera, z-components around -0.33).

**Comment by savuor** [comment]
@ekuznetsov139 I confirm the behavior you've mentioned. Indeed, a slight difference in input data may produce both point P and -P.
I don't know if this is OK or not since we have only 8 3D-2D correspondences so maybe it's better to provide more correspondences to get stable result.
But as you said, providing initial approximations of `rvec` and `tvec` should help.
I'm going to rewrite the function `estimatePoseBoard()` to use user-provided `rvec` and `tvec` values as initial guess when non-empty. Would it be a good solution? Are there any other known functions which should handle the arguments the way I described?

**Comment by ekuznetsov139** [comment]
That is the simplest solution. More generally, though, is it really correct behavior for SolvePnP to return fits that correspond to points being behind the camera?

**Comment by savuor** [comment]
@ekuznetsov139 I'll investigate it.
The `solvePnP` doesn't perform any checks of z coordinates, it calls a `cvProjectPoints2` function at each iteration to get errors and gradients.
Therefore we should find out if it's correct to project points with negative z. If no, then conditions should be added to `cvProjectPoints2` function. If yes, maybe there is a problem in `solvePnP`'s algorithms.

**Comment by savuor** [comment]
Current implementation of iterative `solvePnP` uses to `cvFindExtrinsicCameraParams2` which calls `cvProjectPoints2` to get gradients and projections.
This function doesn't make a difference if a point is behind the camera or not since x/z == (-x)/(-z) (and the same for y).
We cannot forbid to project points with negative z because it breaks iterative solvers work if they start from inappropriate initial guess.
There could be several possible solutions:
* change `cvProjectPoints2` so that it will produce different coordinates and derivates when z < 0 to help iterative solvers to move to z-positive space
* change LevMarq loop in `cvFindExtrinsicCameraParams2` so that it won't call `cvProjectPoints2` but will calculate the projections and derivatives independently
* change initial approximation procedure in the same function to choose between 2 alternatives (but the criteria of the choice isn't clear for me)

@ekuznetsov139 you can implement one of these solutions or propose your own one as new PR.
But now the simpliest solution is to provide better initial guess.

**Comment by JSnader** [comment]
Is the root cause of this negative z-value issue tied to the camera calibration?  
If calibration of the camera does not take into account a target far away from the camera and then we go detecting an Aruco symbol farther away?  Is this the typical reason you might see the values "behind the camera" as described, or is it more complicated than that?
