### ISSUE TITLE
Guided filter might produce wrong results when radius is small

### ISSUE THREAD

**Issue by clarkzjw** [opencv/opencv_contrib#760]
##### System information (version)
- OpenCV => 3.1 (with opencv_contrib compiled)
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2013

##### Detailed description

I have tested OpenCV's implementation of guided filter. And I found that, when the radius is set to a small value, the filtered result is not as expected, compared with the author's MATLAB implementation of guided filter.

##### Steps to reproduce

+ The C++ code I used to test OpenCV's implementation of guided filter
```C++
#include <opencv2\opencv.hpp>
#include <opencv2\ximgproc.hpp>
#include <iostream>
using namespace std;
using namespace cv;

int main()
{
	Mat guide = imread("guide.png");
	Mat input = imread("guide.png", CV_LOAD_IMAGE_GRAYSCALE);
        // Whether input and guide is same or not, the problem both exists.
        // In my case,
        // guide.png is a three-channel RGB image
        // and input is supposed to be an one-channel grayscale image to be filterd
	Mat output = Mat(guide.size(), CV_8UC1, Scalar(0));

	ximgproc::guidedFilter(guide, input, output, 3, 1e-6);
	imwrite("output.bmp", output);

	return 0;
}
```

And the author's MATLAB implementation is [here](http://kaiminghe.com/eccv10/index.html). 

I found that when the radius is set to 1, 3, 5, 7, 9, the output is incorrect. 

For example, when the radius is set to 7, the OpenCV's implementation of guided filter produced the result below. Only part of the image has the correct values.

![output7](https://cloud.githubusercontent.com/assets/2663319/17883980/3a73c214-6948-11e6-9b2e-de3b60397c5a.png)

With the author's MATLAB code, the result is correct while radius and eps is the same.

![matlab7](https://cloud.githubusercontent.com/assets/2663319/17884048/9c530274-6948-11e6-98dc-b706c8c24286.png)

I have read the author's paper about guided filter and implemented guided filter [on my own](https://github.com/clarkzjw/GuidedFilter/blob/master/GuidedFilter/GuidedFilter/guidedfilter.cpp). Although my implementation is slow and lacks optimization, the result I got is the same as the author's MATLAB code. So I believe there must be something wrong in [OpenCV's implementation](https://github.com/opencv/opencv_contrib/blob/master/modules/ximgproc/src/guided_filter.cpp).

@ludv1x Hope you can take a look at this issue at your convenience.

**Comment by ludv1x** [comment]
@clarkzjw Ok, thank you for your feedback :+1: .
I will review it as soon as possible.

**Comment by ludv1x** [comment]
@clarkzjw 
This problem appears when radius is small and regulariztion parameter is small also.
When the radius is small then covariance matrix is poorly conditioned (its determinant is zero) since when radius is small we have a few pixel samples.
It means that its invariance contain a NaN or Inf values and results will contain a lot of NaN values.
So, white areas in provided examples is actually NaNs which were clamped to 255 during imwrite().

Regularization parameter (eps) helps to avoid this problem.
But since OpenCV's implementation uses single precision floating point numbers, too small eps cannot achieve such effect (If you set eps to 1e-2 instead of 1e-6 it will work perfectly).

Original author's implementation uses doubles therefore you can use more small eps there.

I make [a hotfix](https://github.com/ludv1x/opencv_contrib/commit/706ff62f27ea37f99bf61c25a3d483a0ce2f534c#diff-be27a2c85815b166877e1355998285e1R427) of this problem which checks and fix "overflows" (please, not to pay attention to trailing whitespaces).
But I don't assure that described use case (small radius and too small eps) is critical since it is very rare and particularly don't change input image.
What do you think about it?

**Comment by clarkzjw** [comment]
@ludv1x :+1: Well done!

Indeed, I also believe the described usage scenario is rare. In my practical usage, I usually choose a more larger radius. 

I am just curious that why OpenCV's implementation of guided filter uses single precision floating numbers? For compatibility reasons?

**Comment by ludv1x** [comment]
> I am just curious that why OpenCV's implementation of guided filter uses single precision floating numbers? For compatibility reasons?

Single precision floating numbers are ~2x faster than double precision ones.

**Comment by clarkzjw** [comment]
Oh, I see.

And I will try to apply your patch on my local code. If any new usage cases fail, I will let you know. Thank you! :smile:

**Comment by ludv1x** [comment]
@clarkzjw Ok. 
FYI Authors of orignal paper use small eps (0.1^2) assuming that images in [0; 1] range.
So, if you process images in [0; 255] range you should use eps = (0.1 * 255)^2 in such case.

**Comment by clarkzjw** [comment]
All right, thanks for the information.

于 2016年8月26日 GMT+08:00下午6:02:28, Vitaliy Lyudvichenko <notifications@github.com> 写到:
>@clarkzjw Ok. 
>FYI Authors of orignal paper use small eps (0.1^2) assuming that images
>in [0; 1] range.
>So, if you process images in [0; 255] range you should use eps = (0.1 *
>255)^2 in such case.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/opencv/opencv_contrib/issues/760#issuecomment-242687688

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sovrasov** [comment]
@ludv1x can you provide a PR with this patch?
